name: Build on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      working-directory: ./src
      run: sh -c './configure'
    - name: make
      working-directory: ./src
      run: make
    - name: cleanup
      working-directory: ./src
      run: make mrproper
    - name: install
      working-directory: ./src
      run: sudo make install
    - name: packaging test
      working-directory: ./example-pkg
      run: ./compile.sh && PATH="/usr/local/bin:/usr/local/sbin:$PATH" ./package.sh
